# .github/FUNDING.yml

# Enlaces de soporte personalizados para el boton de GitHub
custom: 
  - "https://paypal.me/FranFG"
  - "https://github.com/zoki666/BitcoinKeyHunter#support-the-project"
  - "https://github.com/zoki666/BitcoinKeyHunter/blob/main/README.es.md#apoya-el-proyecto"